version: "3.9"

networks:
  web:
    external: true  # Traefik ya tiene esta red overlay

services:
  app:
    image: ghcr.io/alexisoon/coello:1.0.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.coello.rule=Host(`coello.byronrm.com`)"
        - "traefik.http.routers.coello.entrypoints=websecure"
        - "traefik.http.routers.coello.tls=true"
        - "traefik.http.services.coello.loadbalancer.server.port=5000"
    networks:
      - web
