name: CD - Deploy to VPS

on:
  push:
    branches: ["coello"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Hacer login en GHCR para permitir docker pull en el VPS
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Copiar docker-compose al servidor
      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_SSH_PORT }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.yml"
          target: "/app/coello/"

      # Ejecutar el despliegue automático
      - name: Deploy stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_SSH_PORT }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
            docker pull ghcr.io/${{ github.repository_owner }}/coello:1.0.5
            docker stack deploy --with-registry-auth -c /app/coello/docker-compose.yml coello
