name: CI - Build & Test & Push Image

on:
  push:
    branches: ["coello"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Show project structure
        run: ls -R .

      - name: Install dependencies
        run: |
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
          if [ -f coello/app/requirements.txt ]; then pip install -r coello/app/requirements.txt; fi
          if [ -f coello/requirements.txt ]; then pip install -r coello/requirements.txt; fi

      - name: Run tests inside correct folder
        run: |
          if [ -d coello ]; then cd coello; fi
          pytest -q

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "alexisoon"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/alexisoon/coello:1.0.5 .

      - name: Push image
        run: |
          docker push ghcr.io/alexisoon/coello:1.0.5
